### ISSUE TITLE
Don't fail processing helmreleases with comments between chart,version and sourceRef

### ISSUE THREAD

**Issue by varac** [k8s-at-home/renovate-helm-releases#25]
I have the following HR which doesn't update because it has a comment between chart,version and sourceRef:

```
spec:
  releaseName: sonarr
  chart:
    spec:
        # renovate: registryUrl=https://k8s-at-home.com/charts/
        chart: unifi
        # https://artifacthub.io/packages/helm/k8s-at-home/unifi
        version: 4.4.0
        sourceRef:
            kind: HelmRepository
            name: k8s-at-home
            namespace: flux-system
```

renovate-helm-releases should be not so strict with it's regex and ignore comments.
